[pre-commit]
parallel = true

[pre-commit.commands.check-js]
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc,yml,yaml,svelte}"
run = "pnpm biome check --apply --no-errors-on-unmatched --files-ignore-unknown=true {staged_files} && git update-index --again"

# [pre-commit.commands.check-svelte]
# glob = "*.svelte"
# run = "pnpm svelte-check -- {staged_files} && git update-index --again"

# [pre-commit.commands.update-mdx]
# glob = "*.mdx"
# run = "pnpm scripts/update-mdx {staged_files} && git update-index --again"

[pre-commit.commands.check-toml]
glob = "*.toml"
run = "pnpm taplo format {staged_files} && git update-index --again"

[commit-msg.scripts."commitlint.sh"]
runner = "bash"
