on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm preview
